version: '3'
services:
    frontend:
        container_name: frontend
        env_file:
            - testing.env
        image: terraform.cs.hm.edu:5043/mayerph-graphql-client-starter:master
        ports:
            - '8080:80'
        depends_on:
            - backend
        networks:
            - be
    backend:
        container_name: backend
        env_file:
            - testing.env
        image: terraform.cs.hm.edu:5043/mayerph-grapqhl-server-starter:master
        ports:
            - '8000:8000'
        depends_on:
            - mongo
        networks:
            - be
            - db
            
            
    mongo:
        image: mongo
        networks:
            - db
        volumes:
            - ./data:/data/db
networks:
    be:
    db: